
keys:
  - &users:
    - &user 0581367C097C635BF5839E57282872FA4AF162DE
  - &hosts:
    - &teemo age180avs6dn88g46rahrt7gapdkqf4xvyy6fydnkgt74qrgkvhltsdqhda4v0
creation_rules:
  # General secrets for all users
  - path_regex: home/secrets.yml$
    key_groups:
      - pgp:
        - *user
        age:
        - *teemo
  # Personal secrets for primary user
  - path_regex: home/user/secrets.yml$
    key_groups:
      - pgp:
        - *user
